### ISSUE TITLE
[DI-1] Database Interface frontend

### ISSUE THREAD

**Issue by danqo** [MyMood-Alexa/MyMood#15]
-Start writing the markup portion of the main page, which includes a navigation bar, a table, and pagination
-Screenshots of a working and accepted main page, waiting for backend changes
-Table should reflect the data thats being stored in the database
-Screenshots of json being used and what the table displays

**Comment by jtam360** [comment]
Database Interface Main Page
https://i.gyazo.com/b2097d3aebe04eff03003f1ecfa90199.png

Search Functionality
https://gyazo.com/71af4a8c95567e917d628feebb3d0e18
